"""The database side of NL2SQL safety: a dedicated read-only role, a signed per-question context, and
Postgres row-level security policies that only apply to that role.

LLM-written SQL never runs as Indico's own database user. It runs as ``indico_assistant_ro``:

- SELECT only, on the allowlisted tables and columns (``available_tables.yaml``), nothing else;
- read-only transactions, statement/lock/idle timeouts and a connection limit set on the role;
- row-level security on those tables for that role only: a row is visible if its event is visible under
  the signed context the executor sets per question (``indico_assistant.ctx``). The signature is checked
  inside a SECURITY DEFINER function with a secret the role cannot read, so SQL written by the model
  cannot widen its own scope even if it managed to call ``set_config``.

Visibility rules (``event_id`` scoped questions were already checked with Indico's ``can_access``):

- scoped to one event: only that event (and its non-protected contributions, sessions, attachments...);
- not scoped: effectively public events, plus protected events the user is granted directly or through a
  local group, events inheriting from a category the user may read, and events under a category the
  user manages; admins see everything. Grants through external (multipass) groups, IP networks,
  registrations or access keys are NOT evaluated in SQL: such events are hidden (fails closed).

Setup is a one-time SQL script generated by ``indico assistant nl2sql-db-sql`` and run by a DBA (it
needs the pgcrypto extension, creates the role and enables row-level security on core tables; Indico's
own role is unaffected: owners bypass RLS and a permissive policy covers any non-owner role).
"""

import hashlib
import hmac
import os
from dataclasses import dataclass

from sqlalchemy import create_engine, text


ENV_URI = 'ASSISTANT_NL2SQL_DATABASE_URI'
RO_ROLE = 'indico_assistant_ro'
CONTEXT_SETTING = 'indico_assistant.ctx'

_engines = {}
_secret = {}


class NotConfigured(RuntimeError):
    """NL2SQL has no read-only database configured; it refuses to run rather than fall back."""


@dataclass(frozen=True)
class QueryContext:
    user_id: int
    event_id: int | None
    is_admin: bool

    def payload(self):
        return f'{self.user_id}:{self.event_id or ""}:{int(self.is_admin)}'


def get_engine():
    uri = os.environ.get(ENV_URI)
    if not uri:
        raise NotConfigured(f'The assistant cannot query the database: {ENV_URI} is not set. '
                            f'See the README ("NL2SQL database role").')
    if uri not in _engines:
        # Small pool: the role's CONNECTION LIMIT caps concurrent NL2SQL queries cluster-wide anyway
        _engines[uri] = create_engine(uri, pool_size=2, max_overflow=3, pool_pre_ping=True, pool_recycle=300)
    return _engines[uri]


def connect():
    return get_engine().connect()


def _get_secret():
    if 'value' not in _secret:
        from indico.core.db import db
        try:
            value = db.session.execute(text('SELECT secret FROM plugin_assistant.nl2sql_secret')).scalar()
        except Exception as exc:
            db.session.rollback()
            raise NotConfigured('The NL2SQL database setup script has not been run '
                                '(plugin_assistant.nl2sql_secret is missing).') from exc
        if not value:
            raise NotConfigured('plugin_assistant.nl2sql_secret is empty')
        _secret['value'] = value
    return _secret['value']


def sign(context):
    payload = context.payload()
    signature = hmac.new(_get_secret().encode(), payload.encode(), hashlib.sha256).hexdigest()
    return f'{payload}.{signature}'


# --- setup SQL -------------------------------------------------------------------------------------

# Columns the row policies read; granted alongside the allowlisted columns when the table has them.
POLICY_COLUMNS = ('id', 'event_id', 'category_id', 'contribution_id', 'session_id', 'folder_id', 'attachment_id',
                  'is_deleted', 'protection_mode')

_CTX = '(SELECT {} FROM plugin_assistant.nl2sql_ctx())'
_ADMIN = _CTX.format('is_admin')
_SCOPED = _CTX.format('event_id')
_EVENT_VISIBLE = 'EXISTS (SELECT 1 FROM events.events ev WHERE ev.id = {})'
_NOT_PROTECTED = f'(protection_mode <> 2 OR {_ADMIN})'

POLICIES = {
    'events.events': f'''NOT is_deleted AND CASE
        WHEN {_SCOPED} IS NOT NULL THEN id = {_SCOPED}
        ELSE {_ADMIN}
          OR protection_mode = 1
          OR (protection_mode = 0 AND category_id IN (SELECT plugin_assistant.nl2sql_public_category_ids()))
          OR (protection_mode = 0 AND category_id IN (SELECT plugin_assistant.nl2sql_read_category_ids()))
          OR category_id IN (SELECT plugin_assistant.nl2sql_managed_category_ids())
          OR id IN (SELECT plugin_assistant.nl2sql_granted_event_ids())
        END''',
    'events.contributions': f"NOT is_deleted AND {_NOT_PROTECTED} AND {_EVENT_VISIBLE.format('event_id')}",
    'events.sessions': f"NOT is_deleted AND {_NOT_PROTECTED} AND {_EVENT_VISIBLE.format('event_id')}",
    'events.session_blocks': 'EXISTS (SELECT 1 FROM events.sessions s WHERE s.id = session_id)',
    'events.timetable_entries': _EVENT_VISIBLE.format('event_id'),
    'events.tracks': _EVENT_VISIBLE.format('event_id'),
    'events.contribution_types': _EVENT_VISIBLE.format('event_id'),
    'events.persons': _EVENT_VISIBLE.format('event_id'),
    'events.event_person_links': _EVENT_VISIBLE.format('event_id'),
    'events.contribution_person_links': 'EXISTS (SELECT 1 FROM events.contributions c WHERE c.id = contribution_id)',
    'events.notes': f'''NOT is_deleted AND {_EVENT_VISIBLE.format('event_id')}
        AND (contribution_id IS NULL OR EXISTS (SELECT 1 FROM events.contributions c WHERE c.id = contribution_id))
        AND (session_id IS NULL OR EXISTS (SELECT 1 FROM events.sessions s WHERE s.id = session_id))''',
    'attachments.folders': f'''NOT is_deleted AND {_NOT_PROTECTED} AND event_id IS NOT NULL
        AND {_EVENT_VISIBLE.format('event_id')}
        AND (contribution_id IS NULL OR EXISTS (SELECT 1 FROM events.contributions c WHERE c.id = contribution_id))
        AND (session_id IS NULL OR EXISTS (SELECT 1 FROM events.sessions s WHERE s.id = session_id))''',
    'attachments.attachments': f'''NOT is_deleted AND {_NOT_PROTECTED}
        AND EXISTS (SELECT 1 FROM attachments.folders f WHERE f.id = folder_id)''',
    'attachments.files': 'EXISTS (SELECT 1 FROM attachments.attachments a WHERE a.id = attachment_id)',
    'categories.categories': f'''NOT is_deleted AND ({_ADMIN}
        OR id IN (SELECT plugin_assistant.nl2sql_public_category_ids())
        OR id IN (SELECT plugin_assistant.nl2sql_read_category_ids())
        OR id IN (SELECT plugin_assistant.nl2sql_managed_category_ids()))''',
    'plugin_assistant.extracted_documents': f'''{_EVENT_VISIBLE.format('event_id')}
        AND EXISTS (SELECT 1 FROM attachments.attachments a WHERE a.id = attachment_id)''',
}

_FUNCTIONS = f'''
CREATE OR REPLACE FUNCTION plugin_assistant.nl2sql_ctx(OUT user_id int, OUT event_id int, OUT is_admin boolean)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = pg_catalog, public AS $fn$
DECLARE
    raw text := current_setting('{CONTEXT_SETTING}', true);
    payload text;
BEGIN
    IF raw IS NULL OR raw = '' OR position('.' in raw) = 0 THEN
        RAISE EXCEPTION 'indico assistant: no query context';
    END IF;
    payload := split_part(raw, '.', 1);
    IF encode(hmac(payload, (SELECT secret FROM plugin_assistant.nl2sql_secret LIMIT 1), 'sha256'), 'hex')
            <> split_part(raw, '.', 2) THEN
        RAISE EXCEPTION 'indico assistant: invalid query context';
    END IF;
    user_id := split_part(payload, ':', 1)::int;
    event_id := nullif(split_part(payload, ':', 2), '')::int;
    is_admin := split_part(payload, ':', 3) = '1';
END $fn$;

-- (category id, protecting category id, effective mode 1=public 2=protected); an inheriting root is public
CREATE OR REPLACE FUNCTION plugin_assistant.nl2sql_category_protection()
RETURNS TABLE (category_id int, protecting_id int, mode int)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog AS $fn$
    WITH RECURSIVE t AS (
        SELECT c.id, c.id AS protecting_id, CASE WHEN c.protection_mode = 0 THEN 1 ELSE c.protection_mode END AS mode
        FROM categories.categories c WHERE c.parent_id IS NULL
        UNION ALL
        SELECT c.id,
               CASE WHEN c.protection_mode = 0 THEN t.protecting_id ELSE c.id END,
               CASE WHEN c.protection_mode = 0 THEN t.mode ELSE c.protection_mode END
        FROM categories.categories c JOIN t ON c.parent_id = t.id
    )
    SELECT id, protecting_id, mode FROM t
$fn$;

CREATE OR REPLACE FUNCTION plugin_assistant.nl2sql_user_groups()
RETURNS SETOF int LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog AS $fn$
    SELECT group_id FROM users.group_members WHERE user_id = (SELECT user_id FROM plugin_assistant.nl2sql_ctx())
$fn$;

CREATE OR REPLACE FUNCTION plugin_assistant.nl2sql_public_category_ids()
RETURNS SETOF int LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog AS $fn$
    SELECT category_id FROM plugin_assistant.nl2sql_category_protection() WHERE mode = 1
$fn$;

-- categories whose protecting category grants the user read (or full) access
CREATE OR REPLACE FUNCTION plugin_assistant.nl2sql_read_category_ids()
RETURNS SETOF int LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog AS $fn$
    SELECT cp.category_id FROM plugin_assistant.nl2sql_category_protection() cp
    WHERE cp.mode = 2 AND cp.protecting_id IN (
        SELECT p.category_id FROM categories.principals p
        WHERE (p.read_access OR p.full_access)
          AND (p.user_id = (SELECT user_id FROM plugin_assistant.nl2sql_ctx())
               OR p.local_group_id IN (SELECT plugin_assistant.nl2sql_user_groups())))
$fn$;

-- categories the user manages, and all their descendants (managers can access every event below)
CREATE OR REPLACE FUNCTION plugin_assistant.nl2sql_managed_category_ids()
RETURNS SETOF int LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog AS $fn$
    WITH RECURSIVE m AS (
        SELECT p.category_id AS id FROM categories.principals p
        WHERE p.full_access
          AND (p.user_id = (SELECT user_id FROM plugin_assistant.nl2sql_ctx())
               OR p.local_group_id IN (SELECT plugin_assistant.nl2sql_user_groups()))
        UNION
        SELECT c.id FROM categories.categories c JOIN m ON c.parent_id = m.id
    )
    SELECT id FROM m
$fn$;

CREATE OR REPLACE FUNCTION plugin_assistant.nl2sql_granted_event_ids()
RETURNS SETOF int LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog AS $fn$
    SELECT p.event_id FROM events.principals p
    WHERE (p.read_access OR p.full_access)
      AND (p.user_id = (SELECT user_id FROM plugin_assistant.nl2sql_ctx())
           OR p.local_group_id IN (SELECT plugin_assistant.nl2sql_user_groups()))
$fn$;
'''

_FUNCTION_NAMES = ('nl2sql_ctx()', 'nl2sql_category_protection()', 'nl2sql_user_groups()',
                   'nl2sql_public_category_ids()', 'nl2sql_read_category_ids()', 'nl2sql_managed_category_ids()',
                   'nl2sql_granted_event_ids()')


def _quote_literal(value):
    return "'" + value.replace("'", "''") + "'"


def setup_sql(tables, existing_columns, indico_role, password=None):
    """The one-time setup script.

    :param tables: {table: [allowlisted columns]} from available_tables.yaml
    :param existing_columns: {table: set(columns)} from the live database (unknown columns are skipped)
    :param indico_role: the database role Indico connects as (needs to read the context secret)
    """
    missing = sorted(set(tables) - set(POLICIES))
    if missing:
        raise ValueError(f'No row policy defined for allowlisted table(s): {", ".join(missing)}')
    lines = [
        '-- Indico assistant: read-only NL2SQL role with row-level security. Generated by',
        '-- `indico assistant nl2sql-db-sql`; run as a superuser or the owner of the Indico tables.',
        'BEGIN;',
        'CREATE EXTENSION IF NOT EXISTS pgcrypto;',
        f"DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '{RO_ROLE}') THEN "
        f'CREATE ROLE {RO_ROLE} LOGIN; END IF; END $$;',
        f'ALTER ROLE {RO_ROLE} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS NOREPLICATION CONNECTION LIMIT 20'
        + (f' PASSWORD {_quote_literal(password)}' if password else '') + ';',
        f"ALTER ROLE {RO_ROLE} SET default_transaction_read_only = on;",
        f"ALTER ROLE {RO_ROLE} SET statement_timeout = '10s';",
        f"ALTER ROLE {RO_ROLE} SET lock_timeout = '1s';",
        f"ALTER ROLE {RO_ROLE} SET idle_in_transaction_session_timeout = '15s';",
        f"ALTER ROLE {RO_ROLE} SET work_mem = '16MB';",
        f"ALTER ROLE {RO_ROLE} SET max_parallel_workers_per_gather = 0;",
        '',
        'CREATE TABLE IF NOT EXISTS plugin_assistant.nl2sql_secret (secret text NOT NULL);',
        "INSERT INTO plugin_assistant.nl2sql_secret SELECT encode(gen_random_bytes(32), 'hex') "
        'WHERE NOT EXISTS (SELECT 1 FROM plugin_assistant.nl2sql_secret);',
        'REVOKE ALL ON plugin_assistant.nl2sql_secret FROM PUBLIC;',
        f'GRANT SELECT ON plugin_assistant.nl2sql_secret TO {indico_role};',
        _FUNCTIONS,
    ]
    for name in _FUNCTION_NAMES:
        lines.append(f'REVOKE ALL ON FUNCTION plugin_assistant.{name} FROM PUBLIC;')
        lines.append(f'GRANT EXECUTE ON FUNCTION plugin_assistant.{name} TO {RO_ROLE};')
    schemas = sorted({t.split('.')[0] for t in tables})
    lines.append(f'GRANT USAGE ON SCHEMA {", ".join(schemas)} TO {RO_ROLE};')
    for table in sorted(tables):
        columns = sorted((set(tables[table]) | set(POLICY_COLUMNS)) & existing_columns.get(table, set()))
        lines += [
            '',
            f'REVOKE ALL ON {table} FROM {RO_ROLE};',
            f'GRANT SELECT ({", ".join(columns)}) ON {table} TO {RO_ROLE};',
            f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;',
            f'DROP POLICY IF EXISTS indico_assistant_unrestricted ON {table};',
            f'CREATE POLICY indico_assistant_unrestricted ON {table} AS PERMISSIVE FOR ALL TO PUBLIC '
            f"USING (current_user <> '{RO_ROLE}') WITH CHECK (current_user <> '{RO_ROLE}');",
            f'DROP POLICY IF EXISTS indico_assistant_nl2sql ON {table};',
            f'CREATE POLICY indico_assistant_nl2sql ON {table} AS PERMISSIVE FOR SELECT TO {RO_ROLE} '
            f'USING ({POLICIES[table]});',
        ]
    lines.append('COMMIT;')
    return '\n'.join(lines) + '\n'


def teardown_sql(tables):
    lines = ['BEGIN;']
    for table in sorted(tables):
        lines += [f'DROP POLICY IF EXISTS indico_assistant_nl2sql ON {table};',
                  f'DROP POLICY IF EXISTS indico_assistant_unrestricted ON {table};',
                  f'ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;',
                  f'REVOKE ALL ON {table} FROM {RO_ROLE};']
    lines += [f'DROP FUNCTION IF EXISTS plugin_assistant.{name};' for name in reversed(_FUNCTION_NAMES)]
    lines += ['DROP TABLE IF EXISTS plugin_assistant.nl2sql_secret;',
              f'REVOKE ALL ON ALL TABLES IN SCHEMA {", ".join(sorted({t.split(".")[0] for t in tables}))} '
              f'FROM {RO_ROLE};',
              f'REVOKE USAGE ON SCHEMA {", ".join(sorted({t.split(".")[0] for t in tables}))} FROM {RO_ROLE};',
              f'DROP ROLE IF EXISTS {RO_ROLE};', 'COMMIT;']
    return '\n'.join(lines) + '\n'
