"""SQL generation models for query building.

This module contains Pydantic models for SQL generation and correction,
with built-in safety validation to prevent dangerous queries.
"""

from __future__ import annotations

from pydantic import BaseModel, Field, field_validator


# SQL keywords that are forbidden for safety
_FORBIDDEN_SQL_KEYWORDS = frozenset([
    "DROP", "DELETE", "INSERT", "UPDATE", "CREATE", "ALTER", 
    "TRUNCATE", "GRANT", "REVOKE", "EXEC", "EXECUTE"
])


def _validate_sql_safety(query: str) -> str:
    """Validate SQL query for safety.
    
    Args:
        query: The SQL query to validate.
        
    Returns:
        The validated query.
        
    Raises:
        ValueError: If the query contains forbidden keywords or
                    is not a SELECT statement.
    """
    upper = query.upper().strip()
    
    # Must start with SELECT
    if not upper.startswith("SELECT"):
        raise ValueError("Query must be a SELECT statement")
    
    # Check for forbidden keywords
    for keyword in _FORBIDDEN_SQL_KEYWORDS:
        # Check for keyword as whole word (with word boundaries)
        if f" {keyword} " in f" {upper} ":
            raise ValueError(f"Query cannot contain {keyword}")
    
    return query


class SQLGeneration(BaseModel):
    """LLM-generated SQL query with explanation.
    
    This model represents a SQL query generated by the LLM, including
    an explanation of what the query does and which tables it uses.
    
    Safety validation ensures only SELECT queries are accepted and
    dangerous DDL/DML keywords are rejected.
    
    Attributes:
        query: Generated SQL SELECT statement.
        explanation: Natural language explanation of the query.
        tables_used: List of table names referenced in the query.
    
    Example:
        >>> sql = SQLGeneration(
        ...     query="SELECT e.title, e.start_dt FROM events.events e WHERE e.category_id = 1",
        ...     explanation="Retrieves event titles and start dates for category 1",
        ...     tables_used=["events.events"]
        ... )
    """
    query: str = Field(description="Generated SQL SELECT statement")
    explanation: str = Field(description="Natural language explanation")
    tables_used: list[str] = Field(
        min_length=1,
        description="Table names referenced in query"
    )
    
    @field_validator("query")
    @classmethod
    def validate_query_safety(cls, v: str) -> str:
        """Validate SQL query for safety."""
        return _validate_sql_safety(v)


class SQLCorrection(BaseModel):
    """Corrected SQL query after error feedback.
    
    This model represents a corrected SQL query, generated after
    receiving error feedback from a failed query execution.
    
    Attributes:
        corrected_query: The fixed SQL query.
        error_analysis: Analysis of what was wrong with the original.
        changes_made: List of corrections applied.
    
    Example:
        >>> correction = SQLCorrection(
        ...     corrected_query="SELECT e.title FROM events.events e WHERE e.id = 1",
        ...     error_analysis="The original query referenced a non-existent column 'name'",
        ...     changes_made=["Changed 'name' to 'title'"]
        ... )
    """
    corrected_query: str = Field(description="Fixed SQL query")
    error_analysis: str = Field(description="Analysis of the original error")
    changes_made: list[str] = Field(
        min_length=1,
        description="List of corrections applied"
    )
    
    @field_validator("corrected_query")
    @classmethod
    def validate_query_safety(cls, v: str) -> str:
        """Validate corrected SQL query for safety."""
        return _validate_sql_safety(v)
